-injars kumo-2.0.jar
-injars "..\..\lib\jfoenix-8.0.8.jar"
-outjars kumo-2.0-obf.jar
-target 1.8
-libraryjars "C:\Program Files\Java\jdk1.8.0_201\jre\lib"
 -overloadaggressively
 -obfuscationdictionary ..\..\obfuscation-dictionary.txt
 -classobfuscationdictionary ..\..\windows-dict.txt
-keep class * { public static void main(java.lang.String[]);}
-keep class Server.ClientObject {*;}
-optimizationpasses 3
-allowaccessmodification
-keepparameternames
-dontnote
